"""Add file_path column to Document

Revision ID: 754755227f23
Revises: a20f757f69c7
Create Date: 2025-10-19 14:33:03.880315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754755227f23'
down_revision: Union[str, None] = 'a20f757f69c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_document_table', sa.Column('file_path', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_document_table', 'file_path')
    # ### end Alembic commands ###
